### PR TITLE
DOC: Add CONTRIBUTING and NEWS

### PR DESCRIPTION
**Pull request by mgeier**
Rendered: https://python-rtmixer--33.org.readthedocs.build/en/33/contributing.html

### CODE REVIEW

**Comment by larsoner** [comment]
Thanks @mgeier

**Comment by larsoner** [comment]
Pushing the tags for some reason seems to have not worked with Azure:

https://dev.azure.com/spatialaudio/python-rtmixer/_build?definitionId=1&_a=summary

Might try killing the tag and release, then re-releasing. I messed up the `NEWS.rst` a little bit anyway...

**Comment by larsoner** [comment]
... looks like it's happening to others just as of today:

https://developercommunity.visualstudio.com/content/problem/1157675/tag-triggered-runs-failing-could-not-find-a-servic.html

I also had this problem in `pyvistaqt`. Solved by using the workaround in that thread to manually trigger a "New" run for the tag from the one that failed (at least it's running, hopefully it produces the correct PyPi outputs):

https://dev.azure.com/spatialaudio/python-rtmixer/_build/results?buildId=79&view=results

**Comment by larsoner** [comment]
I am not sure how to update https://readthedocs.org/projects/python-rtmixer/, do I just need to wait longer for it to pick up the PyPi version / GitHub tag?

**Comment by mgeier** [comment]
Thanks for the release!

I don't know how to get the tag onto RTD automatically, but normally I just go to "versions" and "activate" the new one.
Then (when it's successfully built) I go to "admin", "advanced settings" and select the latest version as default.
I should probably have described this in a bit more detail in CONTRIBUTING ...

**Comment by larsoner** [comment]
Okay, all set now I think!

**Comment by mgeier** [comment]
Yes, thanks a lot!

**Pull request merged**
