### PR TITLE
MAINT: Simplify CIBUILDWHEEL command to avoid pip install error

### PR DESCRIPTION
**Pull request by larsoner**
Hopefully fixes https://dev.azure.com/spatialaudio/python-rtmixer/_build/results?buildId=61&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=168f295b-0553-5364-35f7-923225ecd8b3

### CODE REVIEW

**Comment by larsoner** [comment]
Looks like the error is actually not in our command but actually later in `CIBUILDWHEEL`'s. Let's see if removing 3.5 (which is EOL imminently anyway) helps

**Comment by larsoner** [comment]
Okay this one should be good to go @mgeier . Let me know if you want me to remove 3.5 in this PR -- I'm +1 for doing so, it's EOL a few weeks from now. But otherwise this fixes the Azure failure by simplifying the YAML and explicitly sets `python_requires>=3.5` in `setup.py` since that's all we test/build for, and 2.7 reached EOL months ago.

**Comment by mgeier** [comment]
Thanks!

> Let me know if you want me to remove 3.5 in this PR

We should remove it after the next release (which we can make immediately after this PR is done).
If we do it before, Python 2.x users will not be able to install the latest supported version (AFAIK).

**Comment by larsoner** [comment]
Okay, 3.5 bump reverted

**Comment by larsoner** [comment]
@mgeier do you want to push out a release now, or want me to do it?

**Comment by mgeier** [comment]
If you want to do it, please go ahead!

**Pull request merged**
