### PR TITLE
ENH: Add 3.10 support

### PR DESCRIPTION
**Pull request by larsoner**
Hopefully this is all we need to add 3.10 support. If it works I'd like to merge and cut a 1.4 release, hence the version bump here. Okay @mgeier ?

### CODE REVIEW

**Comment by mgeier** [comment]
Thanks for taking care of this!

I've actually tried this a few weeks ago (#47), but it failed and I didn't try again ...

I guess the downgrade of the `portaudio` submodule is unintentional?

**Comment by larsoner** [comment]
> I guess the downgrade of the portaudio submodule is unintentional?

Yeah I'll revert that

Okay to drop 3.6 support as well? It has reached EOL and is breaking our builds

**Comment by larsoner** [comment]
... it wasn't 3.6 that was the problem, I'll put it back.

**Comment by mgeier** [comment]
Thanks @larsoner!

I've enabled the latest version on RTD: https://python-rtmixer.readthedocs.io/en/0.1.4/

**Pull request merged**
