### PR TITLE
MAINT: Bump version

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Comment by larsoner** [comment]
@mgeier feel free to merge if you're happy with the naming, this is I think what would match the PEP spec for version naming

**Comment by mgeier** [comment]
I'm not convinced that's the right thing to do. I've discussed this recently somewhere, but there was no obviously correct way to do this.

Is this in a PEP? Which one?

**Comment by larsoner** [comment]
https://www.python.org/dev/peps/pep-0440/#implicit-development-release-number

**Comment by larsoner** [comment]
(you can do all sorts of complicated schemes like trying to get the `git` version when people import and so forth, but an easy/lazy way to be compliant is to bump and append `.dev0` to the end)

**Comment by mgeier** [comment]
Thanks for the link!

Am I right that tells us *how* those "dev" versions should look like and not *why* we should have them in the first place?

I don't see why doing nothing (i.e. closing this PR) is any worse than merging his PR.

Until I learn about a reason for using "dev" versions (in the way you are suggesting), I prefer to not do any additional steps (which I might forget or mess up in the future).

**Comment by larsoner** [comment]
> I don't see why doing nothing (i.e. closing this PR) is any worse than merging his PR.

It makes it so that anyone who uses the current `master` and does `rtmixer.__version__` still sees 0.1.0 rather than something like `0.2.0.dev0` which clearly indicates (1) they are on a dev version and (2) they are on a version "later" than 0.1.0

**Comment by larsoner** [comment]
... but I'm also fine with closing

**Pull request closed without merging**
