### PR TITLE
ENH: Add 3.8 and bump version

### PR DESCRIPTION
**Pull request by larsoner**
Let's see if this automatically makes 3.8 variants for Linux. I think it should...

### CODE REVIEW

**Comment by larsoner** [comment]
The artifacts look good to me:

https://dev.azure.com/spatialaudio/python-rtmixer/_build/results?buildId=36&view=artifacts&type=publishedArtifacts

And manually downloading the 3.8 Linux wheel and using it works. @drammock can you confirm it works on your system?

**Comment by larsoner** [comment]
@mgeier feel free to merge and I'll push a new GitHub release, which should then cause auto-uploading of new wheels including 3.8 to PyPi

**Comment by drammock** [comment]
I confirm that I can install via `pip install ~/Desktop/deployLinux/rtmixer-0.1.1-cp38-cp38-manylinux1_x86_64.whl `

**Comment by mgeier** [comment]
Thanks!

I normally like to have a clearly recognizable "release commit" (e.g. with a commit message of "Release 0.1.1") that only contains the version bump and possibly a changlog/`NEWS` update, nothing else. This commit should also get the `0.1.1` tag.

So I would prefer to have the CI change in a separate commit, if that's not too much to ask!

**Comment by larsoner** [comment]
Version change reverted, @mgeier feel free to merge/bump/tag/cut a release on GitHub if you want, or I can take care of those steps

**Comment by mgeier** [comment]
Thanks a lot. I'm happy if you would like to make the release!

BTW, do we have the release steps documented somewhere?

**Comment by larsoner** [comment]
No, for this repo with `cibuildwheel` there isn't much to do. Bump version number, release on GitHub (with a tag) and everything end up on PyPi automatically

**Comment by larsoner** [comment]
1. https://github.com/spatialaudio/python-rtmixer/commit/3c082008ccb2249a62cb75542362abfab1467670
2. https://github.com/spatialaudio/python-rtmixer/releases/tag/0.1.1
3. (wait 10 minutes)
4. https://pypi.org/project/rtmixer/0.1.1/#files

**Comment by mgeier** [comment]
Cool, thanks a lot!

I've just done two more steps:

5. activate 0.1.1 on RTD (I don't know if this can be automatic?)
6. set 0.1.1 as default version in advanced RTD settings (I'm fine with doing this manually)

**Comment by mgeier** [comment]
I've documented these steps in #33.

**Pull request merged**
